apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ml-project
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001  # Expose le frontend sur le port 30001
