apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ml-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ouzlaye/ml_project_backend:7  # Remplace <tag> par le tag de l’image sur Docker Hub
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_HOST
          value: "mysql"  # Le nom du service MySQL
